services:
  web:
    image: mikespub/rvolz-bicbucstriim:web
    build:
      context: . 
      dockerfile: docker/Dockerfile.trafex
      target: build
    ports:
      - '8080:8080'
    environment:
      - BBS_APP_NAME=BicBucStriim
      - BBS_BASE_PATH=
      - BBS_DEBUG_MODE=0
      - BBS_HAS_API=1
    volumes:
      - ./data:/var/www/html/data
      - ./config:/var/www/html/config
